from __future__ import annotations

DEFAULT_BATCH_SIZE = 1000
DEFAULT_POOL_MIN_SIZE = 2
DEFAULT_POOL_MAX_SIZE = 10
DEFAULT_AI_MAX_TOKENS = 4096
DEFAULT_AI_PROVIDER = "openai"
DEFAULT_AI_MODEL = "gpt-4o"
BYTES_PER_MB = 1024 * 1024
